### ISSUE TITLE
Issue with Video NFT's minting to IPFS

### ISSUE THREAD

**Issue by centercirclesolutions** [soonaverse/app#71] opened 2023-10-10 19:39 UTC
## Most recent Issue:
> https://discord.com/channels/892481940953915433/1161358770316775434
>
> we are facing a bug with the NFT video data of our collection on Soonaverse: 
> https://soonaverse.com/collection/0x2242ec79d144382687a778ab83f25daf6a74319c
> 
> The video-data of our NFT is not available as preview and the  IPFS link under the "System Info" does also not work:
> https://soonaverse.com/nft/0x27f6edcdf25505dbda12de09ff125a147c43191d
> https://ipfs.io/ipfs/bafkreihdwdcefgh4dqkjv67uzcmw7ojee6xedzdetojuzjevtenxquvyku
> 
> This bug seems to be already known but not fixed: https://github.com/soonaverse/app/issues/67
> 
> Could you please look into this and fix the bug? This seems to be a general problem for all new collections!
> 
> Thank you!  (edited)
> 

## Previous issue: 
> https://discord.com/channels/892481940953915433/1152355784655650836/1152357287210524742

**Comment by adamunchained** [comment] 2023-11-09 17:49
Duplicate of #67

**Comment by flyingrabbit-lab** [comment] 2023-12-18 20:44
It seems that this nft has an empty video.
See here
https://soonaverse.com/nft/0x27f6edcdf25505dbda12de09ff125a147c43191d

**Closed** 2024-01-10 20:27 UTC
